#!/usr/bin/env python
#
# Git pre-commit hook for Esplorio. Serves a number of purposes, including
# testing and code quality
#
import sys
import os
import subprocess
import contextlib


@contextlib.contextmanager
def wrapped_stdin():
    # Since git hooks run with stdin pointed at /dev/tty,
    # connect the two up so we can actually do some user input
    _stdin = sys.stdin
    sys.stdin = open('/dev/tty', 'r')
    yield
    sys.stdin = _stdin


class NoVirtualEnvError(AssertionError):
    msg = "You must have the virtualenv active to run tests!"


class NonZeroReturnCodeError(AssertionError):
    msg = "Failed"


class LintFailedError(AssertionError):
    msg = "Code needs cleanup"


# A list of error / warning / style messages that PyLint shouldn't complain
# about in our code, and which shouldn't abort the commit
PYLINT_IGNORE = [
    'W0614',  # unused modules from wildcard import
    'W0142',  # using *args or **kwargs
    'W0212',  # accessing _id and other 'protected' members
    'C0103',  # *any* 2/3 letter var names (IMO 'db' and 'dt' are OK!)
    'R0914',  # >15 local variables in a function
    'C0301',  # lines >80 chars
    'E1120',  # "no value passed for 'cls' in function call" -- broken
              #    understanding of class methods?
    'E1103',  # 'x' has no 'y' member, but could not infer some types
    # 'E1101',  # 'x' has no 'y' member -- code too dynamic for pylint?
]

# Mappings from file types to lint programs
LINT_MAPPINGS = {
    '.js': ['jsl', '-nosummary', '-nologo', '-process'],
    # Set up pylint to include error message IDs, and not to output the
    # verbose summary report. Also disable the specified error types
    '.py': ['pylint', '-r', 'n', '-i', 'y', '-d', ','.join(PYLINT_IGNORE)]
}

# Some linters have particular rules about how their return codes should be
# handled, e.g. jsl returns a code of 1 on a warning, which we don't think
# is that big a deal
LINT_RETURN_HANDLERS = {
    '.js': lambda x: 0 if x == 1 else x
}

def run_lint_checks():
    # Get list of modified files to run lint checks on
    output = subprocess.check_output(["git", "status", "--porcelain"])
    # git status --porcelain returns a table of statuses and files, like:
    #   M  esplorio/assets/js/main.js
    # Try and run lint on each of the modified files, collecting the return
    # codes in a variable which we check for non-zero (i.e. error) status
    # later.
    overall_retcode = 0
    file_statuses = [l for l in output.split('\n') if l]
    for fs in file_statuses:
        _, filename = fs.split(None, 1)
        # run the appropriate lint based on file type
        _, ftype = os.path.splitext(filename)
        if ftype not in LINT_MAPPINGS:
            continue  # Ignore file types we don't know how to lint
        retcode = subprocess.call(LINT_MAPPINGS[ftype] + [filename])
        if ftype in LINT_RETURN_HANDLERS:
            overall_retcode += LINT_RETURN_HANDLERS[ftype](retcode)
        else:
            overall_retcode += retcode
    if overall_retcode > 0:
        raise LintFailedError()


def run_tests():
    # Provide the option to skip the tests
    with wrapped_stdin():
        reply = raw_input("[Esplorio] Press S to skip, Enter to continue:")
    if reply.lower() == "s":
        return 0
    # Actually run the tests, checking to see if the virtualenv is active first
    print "[Esplorio] running tests using 'manage.py test'..."
    if os.environ.get('VIRTUAL_ENV', '') == '':
        raise NoVirtualEnvError()
    _cmd = "%s/bin/python" % os.environ['VIRTUAL_ENV']
    subprocess.check_call([_cmd, "esplorio/manage.py", "test"])


def main():
    run_lint_checks()
    run_tests()


if __name__ == '__main__':
    try:
        main()
        sys.exit(0)
    except KeyboardInterrupt:
        print '\n\nProgram interrupted. Commit aborted.'
        sys.exit(1)
    except Exception as e:
        print e
        print "[Esplorio] " + getattr(e, "msg", "Error occurred")
        print "Commit aborted."
        sys.exit(1)
